### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by yardasol** [arfc/pygenesys#40] opened 2022-02-28 19:51 UTC
The main `README` file in the repo references an installation option for people who want to contribute to PyGenESys. Consider adding contribution guidelines or a reference/link to contribution guidelines.

This PR can be closed when a PR exists that adds either a file with contribution guidelines to the repo and points to said file in the `README`, or a link in the `README` to some externally located contribution guidelines.

**Comment by munkm** [comment] 2022-02-28 20:06
Related: arfc/pygenesys#25

**Comment by samgdotson** [comment] 2022-03-02 13:04
I'm closing this issue since it is a duplicate of #25

**Closed by samgdotson** 2022-03-02 13:04 UTC
Labels: Difficulty:1-Beginner, Priority:3-Desired, Status:1-New, Type:Docs, Type:Style
